config/routes.rb
Costingtool::Application.routes.draw do
  resources :jobs
  root :to => "jobs#index"
  resources :press_jobs, :only => [:index, :new, :create, :show, :update]
  resources :cost_analyses, :only => [:index, :update]
  resources :dashboards, :only => [:index]
  resources :roi, :only => [:index]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => {:confirmations => 'confirmations', :registrations => 'registrations', :sessions => 'sessions'}
  ActiveAdmin.routes(self)

  devise_scope :user do
    put "/confirm" => "confirmations#confirm"
    post "/users" => "registrations#create"
  end

  match 'jobs/empty_basket' => 'jobs#empty_basket'
  match 'press_jobs/log_presses' => 'press_jobs#log_presses'



end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :name, :number_of_jobs, :copies_per_job, :multicolor_clicks, :black,
                  :number_of_pages, :plex, :sale_price, :annual_growth, :job_percentage, :job_size

  AVAILABLE_SIZES = ['6"x9"', '7"x10"', 'A5', 'A4', 'A3', 'B2']

  validates_inclusion_of :job_size, :in => AVAILABLE_SIZES

  belongs_to :user
  has_many :press_jobs, :dependent => :destroy

  after_save :translate_form_inputs

  serialize :data, ActiveRecord::Coders::Hstore
  hstore :data, :accessors => {
      :number_of_jobs => :integer,
      :copies_per_job => :integer,
      :job_size => :string,
      :multicolor_clicks => :integer,
      :black => :integer,
      :number_of_pages => :integer,
      :plex => :integer,
      :sale_price => :integer,
      :annual_growth => :integer,
      :job_percentage => :integer
  }

  validates_numericality_of :number_of_jobs, :copies_per_job, :multicolor_clicks, :number_of_pages, :sale_price, :annual_growth, :job_percentage

  def translate_form_inputs
    if self.data["black"] == "off" || self.data["black"] == nil
      self.data["black"] = 0
      self.save
    elsif data["black"] == "on"
      self.data["black"] = 1
      self.save
    else
    end

    self.data["plex"] == "Duplex" ? self.plex = 2 : self.plex = 1
  end

  def self.available_sizes
    AVAILABLE_SIZES.to_a
  end

  def css_name
    self.name.downcase.split(" ").join("-").sub(/\W/, '')
  end

  def copies_per_month
    self.number_of_jobs * self.copies_per_job
  end

  def pages_per_month
    copies_per_month * self.number_of_pages
  end

end

app/views/layouts/_cost-analysis.html.erb
<div class="press-cost-summary-container">
  <div class="press-cost-summary-navigation" >
    <%= link_to '<i class="foundicon-left-arrow icon-tiny next-arrow press-cost-summary-carousel"></i>'.html_safe, "#" %>
    <h3 class="subheader inline-header"><%= job.name %></h3>
    <%= link_to '<i class="foundicon-right-arrow icon-tiny next-arrow press-cost-summary-carousel"></i>'.html_safe, "#" %>
  </div>
  <div class="left-press">
    <%= image_tag("#{PressJob.newest(job.press_jobs).press_type.icon.url(:small) if PressJob.newest(job.press_jobs).press_type.icon.present?}") %>
    <h4 class="subheader"><%= PressJob.newest(job.press_jobs).press_type.name %> </h4>
        <table class="cost-analysis-table">
          <tr>
            <td width="140"><p>Hardware</p></td>
            <td width="100"><%= "#{number_to_currency PressJob.newest(job.press_jobs).press_cost}"%></td>
          </tr>
          <tr>
            <td width="140"><p>Media</p></td>
            <td width="100"><%= "#{number_to_currency PressJob.newest(job.press_jobs).calculated_media_cost.to_f.round(2)}"%></td>
          </tr>
          <tr>
            <td width="140"><p>Labor</p></td>
            <td width="100"><%= "#{number_to_currency PressJob.newest(job.press_jobs).labor_cost}"%></td>
          </tr>
          <tr>
            <td width="140"><p>Service</p></td>
            <td width="100"><%= "#{number_to_currency PressJob.newest(job.press_jobs).spi_cost.to_f.round(2)}"%></td>
          </tr>
          <tr>
            <td width="140"><p>Clicks</p></td>
            <td width="100"><%= "#{number_to_currency PressJob.newest(job.press_jobs).calculated_clicks_cost.to_f.round(2)}"%></td>
          </tr>
          <tr>
            <td width="140"><strong>Total</strong></td>
            <td width="100"><strong><%= "#{number_to_currency PressJob.newest(job.press_jobs).calculated_total_cost.to_f.round(2)}"%></strong></td>
          </tr>
        </table>
        <br />
        <table class="cost-analysis-table">
          <tr>
            <td width="140"><p>Cost per Job</p></td>
            <td width="100"><%= "#{number_to_currency PressJob.newest(job.press_jobs).calculated_cost_per_job.to_f.round(2)}"%></td>
          </tr>
          <tr>
            <td width="140"><p>Cost per Copy</p></td>
            <td width="100"><%= "#{number_to_currency PressJob.newest(job.press_jobs).calculated_cost_per_copy.to_f.round(2)}"%></td>
          </tr>
          <tr>
            <td width="140"><p>No. jobs per month</p></td>
            <td width="100"><%= "#{PressJob.newest(job.press_jobs).number_of_jobs}"%></td>
          </tr>
          <tr>
            <td width="140"><p>Copies per job</p></td>
            <td width="100"><%= "#{PressJob.newest(job.press_jobs).copies_per_job}"%></td>
          </tr>
        </table>
  </div>
  <% if PressJob.newest(job.press_jobs) != PressJob.oldest(job.press_jobs) %>
      <div class="right-press">
        <%= image_tag("#{PressJob.oldest(job.press_jobs).press_type.icon.url(:small) if PressJob.oldest(job.press_jobs).press_type.icon.present?}") %>
        <h4 class="subheader"><%= PressJob.oldest(job.press_jobs).press_type.name %> </h4>
            <table class="cost-analysis-table">
              <tr>
                <td width="140"><p>Hardware</p></td>
                <td width="100"><%= "#{number_to_currency PressJob.oldest(job.press_jobs).press_cost}"%></td>
              </tr>
              <tr>
                <td width="140"><p>Media</p></td>
                <td width="100"><%= "#{number_to_currency PressJob.oldest(job.press_jobs).calculated_media_cost.to_f.round(2)}"%></td>
              </tr>
              <tr>
                <td width="140"><p>Labor</p></td>
                <td width="100"><%= "#{number_to_currency PressJob.oldest(job.press_jobs).labor_cost}"%></td>
              </tr>
              <tr>
                <td width="140"><p>Service</p></td>
                <td width="100"><%= "#{number_to_currency PressJob.oldest(job.press_jobs).spi_cost.to_f.round(2)}"%></td>
              </tr>
              <tr>
                <td width="140"><p>Clicks</p></td>
                <td width="100"><%= "#{number_to_currency PressJob.oldest(job.press_jobs).calculated_clicks_cost.to_f.round(2)}"%></td>
              </tr>
              <tr>
                <td width="140"><strong>Total</strong></td>
                <td width="100"><strong><%= "#{number_to_currency PressJob.oldest(job.press_jobs).calculated_total_cost.round(2)}"%></strong></td>
              </tr>
            </table>
            <br />
            <table class="cost-analysis-table">
              <tr>
                <td width="140"><p>Cost per Job</p></td>
                <td width="100"><%= "#{number_to_currency PressJob.oldest(job.press_jobs).calculated_cost_per_job.to_f.round(2)}"%></td>
              </tr>
              <tr>
                <td width="140"><p>Cost per Copy</p></td>
                <td width="100"><%= "#{number_to_currency PressJob.oldest(job.press_jobs).calculated_cost_per_copy.to_f.round(2)}"%></td>
              </tr>
              <tr>
                <td width="140"><p>No. jobs per month</p></td>
                <td width="100"><%= "#{PressJob.oldest(job.press_jobs).number_of_jobs}"%></td>
              </tr>
              <tr>
                <td width="140"><p>Copies per job</p></td>
                <td width="100"><%= "#{PressJob.oldest(job.press_jobs).copies_per_job}"%></td>
              </tr>
            </table>
      </div>
  <% end %>

</div>

app/views/layouts/_press-cost-summary-constants.html.erb
<div class="press-cost-summary-container">
  <div class="left-press">
    <%= form_for(PressJob.newest(job.press_jobs), :remote => true) do |f| %>
        <table class="press-job-values-table">
          <tr>
            <td width="200"><p style="font-size: small;">Press Price</p></td>
            <td width="100"><%= f.text_field :press_price, :class => "press-job-values zero-decimal", :id => "update_press_price_#{PressJob.newest(job.press_jobs).id}", :placeholder => "$#{enforce_float_zeros(PressJob.newest(job.press_jobs).press_price, 0)}" %></td>
          </tr>
          <tr>
            <td width="200"><p style="font-size: small;">Monthly Labor Cost</p></td>
            <td width="100"><%= f.text_field :labor_cost, :class => "press-job-values zero-decimal", :id => "update_labor_cost_#{PressJob.newest(job.press_jobs).id}", :placeholder => "$#{enforce_float_zeros(PressJob.newest(job.press_jobs).labor_cost, 0)}" %></td>
          </tr>
          <tr>
            <td width="200"><p style="font-size: small;">Monthly SPI</p></td>
            <td width="100"><%= f.text_field :spi_cost, :class => "press-job-values zero-decimal", :id => "update_spi_cost_#{PressJob.newest(job.press_jobs).id}", :placeholder => "$#{enforce_float_zeros(PressJob.newest(job.press_jobs).calculated_spi_cost, 2)}" %></td>
          </tr>
        </table>
    <% end %>
  </div>
  <% if PressJob.newest(job.press_jobs) != PressJob.oldest(job.press_jobs) %>
      <div class="right-press">
        <%= form_for(PressJob.oldest(job.press_jobs), :remote => true) do |f| %>
            <table class="press-job-values-table">
              <tr>
                <td width="200"><p style="font-size: small;">Press Price</p></td>
                <td width="100"><%= f.text_field :press_price, :class => "press-job-values zero-decimal", :id => "update_press_price_#{PressJob.oldest(job.press_jobs).id}", :placeholder => "$#{enforce_float_zeros(PressJob.oldest(job.press_jobs).press_price, 0)}" %></td>
              </tr>
              <tr>
                <td width="200"><p style="font-size: small;">Monthly Labor Cost</p></td>
                <td width="100"><%= f.text_field :labor_cost, :class => "press-job-values zero-decimal", :id => "update_labor_cost_#{PressJob.oldest(job.press_jobs).id}", :placeholder => "$#{enforce_float_zeros(PressJob.oldest(job.press_jobs).labor_cost, 0)}" %></td>
              </tr>
              <tr>
                <td width="200"><p style="font-size: small;">Monthly SPI</p></td>
                <td width="100"><%= f.text_field :spi_cost, :class => "press-job-values zero-decimal", :id => "update_spi_cost_#{PressJob.oldest(job.press_jobs).id}", :placeholder => "$#{enforce_float_zeros(PressJob.oldest(job.press_jobs).calculated_spi_cost, 2)}" %></td>
              </tr>
            </table>
        <% end %>
      </div>
  <% end %>
</div>

app/views/layouts/_press-cost-summary.html.erb
<div class="press-cost-summary-container">
  <div class="press-cost-summary-navigation" >
    <%= link_to '<i class="foundicon-left-arrow icon-tiny next-arrow press-cost-summary-carousel"></i>'.html_safe, "#" %>
    <h3 class="subheader inline-header"><%= job.name %></h3>
    <%= link_to '<i class="foundicon-right-arrow icon-tiny next-arrow press-cost-summary-carousel"></i>'.html_safe, "#" %>
  </div>
  <div class="left-press">
    <%= image_tag("#{PressJob.newest(job.press_jobs).press_type.icon.url(:small) if PressJob.newest(job.press_jobs).press_type.icon.present?}") %>
    <h4 class="subheader"><%= PressJob.newest(job.press_jobs).press_type.name %> </h4>
    <%= form_for(PressJob.newest(job.press_jobs), :remote => true) do |f| %>
        <table class="press-job-values-table">
              <tr>
                <td width="200"><p style="font-size: small;"><%= job.job_size %> Cost / Sheet</p></td>
                <td width="100"><%= f.text_field :cost_per_sheet, :class => "press-job-values five-decimal", :id => "update_cost_per_sheet_#{PressJob.newest(job.press_jobs).id}", :value => "$#{enforce_float_zeros(PressJob.newest(job.press_jobs).cost_per_sheet, 2)}" %></td>
              </tr>
              <tr>
                <td width="200"><p style="font-size: small;">Click Price</p></td>
                <td width="100"><%= f.text_field :click_price, :class => "press-job-values two-decimal", :id => "update_click_price_#{PressJob.newest(job.press_jobs).id}", :value => "$#{enforce_float_zeros(PressJob.newest(job.press_jobs).click_price, 5)}" %></td>
              </tr>
        </table>
    <% end %>
  </div>
  <% if PressJob.newest(job.press_jobs) != PressJob.oldest(job.press_jobs) %>
      <div class="right-press">
        <%= image_tag("#{PressJob.oldest(job.press_jobs).press_type.icon.url(:small) if PressJob.oldest(job.press_jobs).press_type.icon.present?}") %>
        <h4 class="subheader"><%= PressJob.oldest(job.press_jobs).press_type.name %> </h4>
        <%= form_for(PressJob.oldest(job.press_jobs), :remote => true) do |f| %>
            <table class="press-job-values-table">
              <tr>
                <td width="200"><p style="font-size: small;"><%= job.job_size %> Cost / Sheet</p></td>
                <td width="100"><%= f.text_field :cost_per_sheet, :class => "press-job-values five-decimal", :id => "update_cost_per_sheet_#{PressJob.oldest(job.press_jobs).id}", :value => "#{enforce_float_zeros(PressJob.oldest(job.press_jobs).cost_per_sheet, 2)}" %></td>
              </tr>
              <tr>
                <td width="100"><p style="font-size: small;">Clicks Price</p></td>
                <td width="100"><%= f.text_field :click_price, :class => "press-job-values two-decimal", :id => "update_click_price_#{PressJob.oldest(job.press_jobs).id}", :value => "#{enforce_float_zeros(PressJob.oldest(job.press_jobs).click_price, 5)}" %></td>
              </tr>
            </table>
        <% end %>
      </div>
  <% end %>
</div>

app/views/layouts/_roi.html.erb
<div class="press-cost-summary-container">
  <div class="press-cost-summary-navigation" >
    <%= link_to '<i class="foundicon-left-arrow icon-tiny next-arrow press-roi-carousel"></i>'.html_safe, "#" %>
    <h3 class="subheader inline-header"><%= press_job.press_type.name %></h3>
    <%= link_to '<i class="foundicon-right-arrow icon-tiny next-arrow press-roi-carousel"></i>'.html_safe, "#" %>
  </div>
  <br>

  <div id="chart_<%= press_job.id %>" class="roi-chart"></div>

  <table id="table_<%= press_job.id %>" class="roi-table">
    <tr>
      <th>ROI</th>
      <th>Payback Period (Months)</th>
      <th>Total Profit</th>
      <th>Total Costs</th>
      <th>Production Life (Months)</th>
    </tr>
    <tr>
      <td><%= press_job.press_roi %>%</td>
      <td><%= press_job.press_payback_period %></td>
      <td><%= number_to_currency(press_job.press_total_profit, :precision => 0) %></td>
      <td><%= number_to_currency(press_job.press_total_costs, :precision => 0) %></td>
      <td><%= press_job.press_production_life %></td>
    </tr>
  </table>
</div>



<script language="javascript">
    window.press_job_ids = <%= @press_job_ids %>;
    window.costs = <%=raw @roi_costs.to_json %>;
    window.revenue = <%=raw @roi_revenue.to_json %>;
</script>

app/views/layouts/_steps.html.erb
<div class="step job-basket">
  <%= current_process_step > 1 ? link_to("1. Basket", jobs_path) : "1. Basket" %>
</div>
<div class="step press-select">
  <%= current_process_step > 2 ? link_to("2. Press", new_press_job_path) : "2. Select" %>
</div>
<div class="step press-cost-summary">
  <%= current_process_step > 3 ? link_to("3. Summary", press_jobs_path) : "3. Summary" %>
</div>
<div class="step cost-analysis">
  <%= current_process_step > 3 ? link_to("4. Costs", cost_analyses_path) : "4. Costs" %>
</div>
<div class="step roi">
  <%= current_process_step > 3 ? link_to("5. ROI", roi_index_path) : "5. ROI" %>
</div>

app/views/layouts/_top-bar.html.erb
<%= image_tag("hp_logo_tiny.png", :class => "hp_logo tiny-logo") %>
<h4 class="brand"> Indigo ROI Calculator</h4>
<h5 class="brand"> Sheet Feed Commercial Presses</h5>

<i data-dropdown="drop1" class="foundicon-settings icon-medium gear dropdown"></i>


<ul id="drop1" class="f-dropdown right-sided-dropdown">
  <li><%= link_to "Reset Session", jobs_empty_basket_path, :method => :post, data: { confirm: 'Are you sure you want to reset session?' }%></li>
  <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "HP Costing Tool" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= favicon_link_tag "hpcosting.ico"  %>
    <%= csrf_meta_tags %>

    <!-- the following script allows the creation of Pivotal Tracker bugs directly from the web pages -->
    <!--<script id="redline_js" type="text/javascript">var redline = {}; redline.project_id = 119611082;var b,d;b=document.createElement("script");b.type="text/javascript";b.async=!0;b.src=("https:"===document.location.protocol?"https://data":"http://www")+'.redline.cc/assets/button.js';d=document.getElementsByTagName("script")[0];d.parentNode.insertBefore(b,d);</script>-->
  </head>

  <body>

    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>